name: C++ CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Dependencies
      run: sudo apt-get install -y build-essential libgtest-dev
    - name: main make
      run: make
    - name: test make
      run: make test
    - name: chmod
      run: chmod +x test_runner
    - name: test
      run: ./test_runner
